DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE(
  ID INT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(60) NOT NULL
  , SURNAME VARCHAR(40) NOT NULL
  , BIRTH_DATE DATE
  , RATING DOUBLE DEFAULT 1
  , DESCRIPTION VARCHAR(200)
  , COUNTRY_ID INT DEFAULT 1
  , PHOTO_PATH VARCHAR(200)
  , PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYER(
  ID INT NOT NULL AUTO_INCREMENT
  , ORGANIZATION VARCHAR(60) NOT NULL
  , VERIFICATION BIT
  , CONTACTS VARCHAR(60)
  , PRIMARY KEY (ID)
);

CREATE TABLE COUNTRY(
  COUNTRY_ID INT NOT NULL
  , COUNTRY_NAME VARCHAR(60) NOT NULL
  , PRIMARY KEY (COUNTRY_ID)
);

CREATE TABLE PROFESSION(
  PROF_ID INT NOT NULL
  , PROF_NAME VARCHAR(60) NOT NULL
  , PRIMARY KEY (PROF_ID)
);

CREATE TABLE REQUEST(
  REQ_ID INT NOT NULL AUTO_INCREMENT
  , EMPL_ID INT
  , COUNTRY_ID INT
  , PROF_ID INT
  , MIN_SALARY INT
  , MAX_SALARY INT
  , HOUSE BIT
  , PRIMARY KEY (REQ_ID)
);

CREATE TABLE VACANCY(
  VACANCY_ID INT NOT NULL AUTO_INCREMENT
  , EMPL_ID INT
  , COUNTRY_ID INT
  , PROF_ID INT
  , MIN_SALARY INT
  , MAX_SALARY INT
  , HOUSE BIT
  , PRIMARY KEY (VACANCY_ID)
);

CREATE TABLE EMPLOYEE_GRADE(
  GRADE_ID INT NOT NULL AUTO_INCREMENT
  , COMMENT VARCHAR (200)
  , MARK INT
  , EMPL_ID INT
  , PRIMARY KEY (GRADE_ID)
);

CREATE TABLE EMPLOYER_GRADE(
  GRADE_ID INT NOT NULL AUTO_INCREMENT
  , COMMENT VARCHAR (200)
  , MARK INT
  , EMPL_ID INT
  , PRIMARY KEY (GRADE_ID)
);

-- CREATE TABLE PHOTO(
--   PHOTO_ID INT NOT NULL AUTO_INCREMENT
--   , PHOTO BLOB
--   , PRIMARY KEY (PHOTO_ID)
-- );